global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'null'

receivers:
- name: 'null'
  webhook_configs:
  - url: 'http://localhost:5001/' # Dummy webhook

